import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Type-aware rules (no-floating-promises, no-misused-promises, no-unsafe-*)
  // on top of the syntax-only typescript-eslint rules from eslint-config-next.
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  // clsx + tailwind-merge is our cn(); shadcn's base-nova registry imports
  // the "cn" package instead, so components added via `shadcn add` must be fixed.
  {
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "cn",
              message:
                'Import { cn } from "@/lib/utils" and remove the "cn" dependency.',
            },
          ],
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    // Playwright output (ESLint does not read .gitignore).
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
    // Claude Code worktrees of this repo (other sessions' checkouts).
    ".claude/worktrees/**",
    // Docker volumes; on Linux they belong to container users and can't be read.
    ".data/**",
    // Prisma Client, generated by `prisma generate`.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
