import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";
import shelter from "./eslint/ledger-boundary.mjs";

// esquery regex literals: hex colours and colour functions (color-mix() over
// tokens is fine), and classes of Tailwind's default palette.
const COLOR_LITERAL =
  "/#(?:[0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})\\b|\\b(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch)\\(/i";
const DEFAULT_PALETTE_CLASS =
  "/\\b(?:bg|text|border(?:-[trblxyse])?|ring(?:-offset)?|outline|fill|stroke|from|via|to|decoration|accent|caret|divide|placeholder|shadow|inset-shadow|drop-shadow|text-shadow)-(?:black|white|slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)\\b/";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Type-aware rules (no-floating-promises, no-misused-promises, no-unsafe-*)
  // on top of the syntax-only typescript-eslint rules from eslint-config-next.
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  // clsx + tailwind-merge is our cn(); shadcn's base-nova registry imports
  // the "cn" package instead, so components added via `shadcn add` must be fixed.
  {
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "cn",
              message:
                'Import { cn } from "@/lib/utils" and remove the "cn" dependency.',
            },
          ],
        },
      ],
    },
  },
  // Colours come only from the design tokens in src/app/globals.css
  // (docs/design.md#токены-в-коде). Tailwind's default palette is switched
  // off there, so its classes would silently generate nothing.
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        // Anchors such as href="#feed" look like hex colours: skip them.
        ...[
          "Literal[value=%s]:not(JSXAttribute[name.name=/^(?:href|id|htmlFor)$/] > Literal)",
          "TemplateElement[value.raw=%s]",
        ].flatMap((selector) => [
          {
            selector: selector.replace("%s", COLOR_LITERAL),
            message:
              "Use a colour token (bg-paper, text-pen, var(--color-toner)…) instead of a colour value.",
          },
          {
            selector: selector.replace("%s", DEFAULT_PALETTE_CLASS),
            message:
              "Tailwind's default palette is disabled: use a colour token (bg-paper, text-toner…).",
          },
        ]),
      ],
    },
  },
  // Only src/server/ledger touches the Ledger* tables (docs/ledger.md). Its
  // integration tests check the triggers, so they write to the tables directly.
  {
    files: ["**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}"],
    ignores: [
      "src/server/ledger/**",
      "tests/integration/ledger/**",
      "eslint/ledger-boundary.test.ts",
    ],
    plugins: { shelter },
    rules: { "shelter/ledger-boundary": "error" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    // Playwright output (ESLint does not read .gitignore).
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
    // Claude Code worktrees of this repo (other sessions' checkouts).
    ".claude/worktrees/**",
    // Docker volumes; on Linux they belong to container users and can't be read.
    ".data/**",
    // Prisma Client, generated by `prisma generate`.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
